### PR TITLE
Added a default meta if not specified for certain blocks

### LINKED ISSUE #93: Default direction of block entities like chest should be changed
Copied from [cuberite#2506](https://github.com/cuberite/cuberite/issues/2506)

The default direction of this blocks: ladder, furnace, chest and trapped chest should be 2 instead of 0.
Allowed values are 2, 3, 4, and 5.
I had a problem with setting chests, because I had the meta value 0 and then the block was always invisible.
In Bukkit other values then them above are not allowed. WorldEdit (java one) defaults to 2, if a invalid value is used. Bukkit defaults to 5, don't know why, but I think 2 is better.

How and where should this be implemented in the code?

### PR DESCRIPTION
**Pull request by NiLSPACE**
Fixes #93 
@Seadragon91 are there more blocks? I've already tried vines, but that one seemed to work normally with meta 0.

### CODE REVIEW

**Comment by Seadragon91** [comment]
E_BLOCK_WALLSIGN and E_BLOCK_WALL_BANNER with meta 2. Then I think we have all.

**Comment by NiLSPACE** [comment]
Then I'm done now I guess :)

**Comment by Seadragon91** [comment]
Okay heads with data value 0 are visible and can be placed, let's ignore them.

LGTM :)

**Comment by NiLSPACE** [comment]
Heads with meta 0 aren't visible for me ;O

**Pull request merged**
