### PR TITLE
Added a storage system. The last player selections are saved

### PR DESCRIPTION
**Pull request by NiLSPACE**
**DO NOT MERGE**
You can now logout and when coming back your selection is still there.

I'm still thinking if I should move the loading/saving to the cSQLStorage class instead of doing it in the class where the info is actually used. Any thoughts? @cuberite/plugin-contributors?

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Any objections?

**Comment by SphinxC0re** [comment]
Well there are a few missing newlines and git doesn't like that but leaving that this seems okay

**Comment by NiLSPACE** [comment]
I've always wondered why Github doesn't like that. Does anyone know?

**Comment by SphinxC0re** [comment]
It's not about GitHub not liking it. It's git. It has something to do with merging

**Pull request merged**
