### PR TITLE
Added backup functionality when updating database

### PR DESCRIPTION
**Pull request by NiLSPACE**

### CODE REVIEW

**Comment by NiLSPACE** [comment]
Don't merge this yet. I forgot to change something.

**Comment by NiLSPACE** [comment]
There, done.

**Comment by NiLSPACE** [comment]
There, I'm done now.

**Comment by NiLSPACE** [comment]
Merge?

**Comment by SphinxC0re** [comment]
Like I said before, git diesn like these missing newlines. Could you please just add them for consistency?

**Comment by NiLSPACE** [comment]
I still don't get why Git doesn't like that, but whatever, I added them.

**Comment by SphinxC0re** [comment]
Looks good

**Pull request merged**
